name: HTML5 Validator
on: push
jobs:
  html_eval:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: validate
        uses: chabad360/htmlproofer@master
        with:
          directory: ./templates
